### PR TITLE
Nuxt 3 Starter Kit

### PR DESCRIPTION
**Pull request by dvanmali**
A simple Nuxt 3 starter kit application. https://github.com/dvanmali/surrealdb-nuxt-starter

If you have an existing Nuxt 3 project setup, a server-side [Nitro Plugin](https://github.com/dvanmali/surrealdb-nuxt-starter/blob/main/server/plugins/surrealdb.ts) can be copied over to your existing project.

### CODE REVIEW

**Review by kearfy — COMMENTED** [review]
Hey @dvanmali, could you include a screenshot of your application running in the README of your project? Thanks!

**Comment by dvanmali** [comment]
Hey @kearfy @timpratim, updated the docs with images and contribution guidelines :)

**Comment by timpratim** [comment]
Hey @dvanmali , we can go ahead and merge the PR once the merge conflict is resolved.

**Comment by dvanmali** [comment]
Done @timpratim

**Comment by dvanmali** [comment]
Hi @naisofly, I opened this for #35 Hacktoberfest a month ago, can you merge please :)

**Comment by timpratim** [comment]
Hey @dvanmali , merging the PR.

**Comment by naisofly** [comment]
Well done @dvanmali!
Thank you for contributing to SurrealDB during Hacktoberfest 2023 🎉
Kindly send an email to [community@surrealdb.com](mailto:community@surrealdb.com) to coordinate the delivery of your SurrealDB swag! 😁

**Pull request merged**
