### PR TITLE
Added Vue Starter Kit (Hacktoberfest)

### PR DESCRIPTION
**Pull request by inkollusireeshaadharani**
This is a simple task manager application built using Vue.js.
https://github.com/inkollusireeshaadharani/vue-starter-kit
Kindly let me know if there are changes to be made!

### CODE REVIEW

**Comment by naisofly** [comment]
Nice work @inkollusireeshaadharani!
Were you going for a CRUD app here & yet to build the Update functionality? 
Let @Ekwuno & I know if you need any guidance here ✌️

**Comment by inkollusireeshaadharani** [comment]
hi @naisofly. Thanks for reviewing the code. I was not going for a CRUD app to keep it simple. Do you want me to add update functionality?

**Comment by naisofly** [comment]
Hey @inkollusireeshaadharani, it would be great if you added update functionality too but it's not required to merge this PR.

**Comment by naisofly** [comment]
@inkollusireeshaadharani, will do. Can you kindly resolve the conflicts so I can merge?

**Comment by inkollusireeshaadharani** [comment]
hi @naisofly. I have resolved the merge conflict.

**Review by naisofly — COMMENTED** [review]
Well done @inkollusireeshaadharani!
Thank you for contributing to SurrealDB during Hacktoberfest 2023 🎉
Kindly send an email to [community@surrealdb.com](mailto:community@surrealdb.com) to coordinate the delivery of your SurrealDB swag! 😁

**Comment by inkollusireeshaadharani** [comment]
I am so glad to have worked with SurrealDB. Looking forward to explore and build more amazing projects using it. Thank you for the awesome support👍🏻 @naisofly

**Pull request merged**
