### PR TITLE
React+Node starter

### PR DESCRIPTION
**Pull request by MSaiKiran9**
My contribution for the issue #35 

This starter contains front-end and backend app made with react and nodejs . More info is available in the Readme: https://github.com/MSaiKiran9/react.nodejs_starter#readme

If there's something that should be improved, do let me know !

### CODE REVIEW

**Comment by kearfy** [comment]
Hello @MSaiKiran9! Thanks for your Pull Request! I read through the code, and I have a comment on the way that you fetch data in the frontend. It is generally not recommended to use a state and an effect to handle data fetching in React, as it causes unexpected issues. Data fetching can be quite a difficult problem in React, but there are some amazing libraries out there that handle the boilerplate for you, and I thought it might be an idea to implement one of them 😃 

Notably:
- https://tanstack.com/query/latest
- https://swr.vercel.app/
- (and probably many more)

Would you consider using refactoring this bit of code? Let me know if you need any help!

Thanks ❤️ 

PS: Feel free to take a look at [my project](https://github.com/theopensource-company/playrbase/tree/main) where I implement surrealdb.js with React myself 😃

**Comment by MSaiKiran9** [comment]
@kearfy I've refactored the code and also used swr to update the frontend's UI every 10 seconds with the database data if it has any updates . swr is really awesome .Thanks for the suggestion & let me know it it's okay now

**Comment by MSaiKiran9** [comment]
Hi @kearfy let me know if this starter is good to go now

**Comment by MSaiKiran9** [comment]
Hi @Ekwuno @kearfy can you confirm if this is okay

**Comment by kearfy** [comment]
Hey @MSaiKiran9, your email got buried in my inbox, apologies! Will have a look tonight

**Comment by kearfy** [comment]
Awesome @MSaiKiran9, your changes look good, thanks! Last question: Could you update this PR so that there are no conflicts and so everything is in order?

**Review by kearfy — APPROVED** [review]

**Comment by MSaiKiran9** [comment]
Thankyou @kearfy

**Comment by naisofly** [comment]
Hey @MSaiKiran9 
Thank you for contributing to SurrealDB during Hacktoberfest 2023 🎉
Kindly send an email to [community@surrealdb.com](mailto:community@surrealdb.com) to coordinate the delivery of your SurrealDB swag! 😁

**Pull request merged**
