### PR TITLE
Add nextjs tauri kit in README.md

### PR DESCRIPTION
**Pull request by reymom**
My contribution for the issue [#35](https://github.com/surrealdb/awesome-surreal/issues/35).

From the [README.md](https://github.com/reymom/surrealdb-starter-taurikit#readme): This starter kit provides a streamlined setup for developing a Tauri App + Next.js applications with an integrated [SurrealDB](https://surrealdb.com/) database. It bridges the frontend with the backend using an ICP command layer following the JSON-RPC 2.0 format.

If there's something that should be improved, do let me know :+1:

### CODE REVIEW

**Review by phughk — APPROVED** [review]
Great submission, thank you!

**Comment by reymom** [comment]
Thanks for the feedback! I already added the tauri-cli install command. I will also check that about the structure, I agree it looks a bit odd. I was trying to get a minimal organization and ended up mixing types-model-storage up.

**Comment by kearfy** [comment]
Apologies for the delayed merge here @reymom! Merged it now, thanks for your contribution!

**Comment by kearfy** [comment]
Oh, I forgot to ask, but could you add a screenshot of your finished application in the Readme of your project?

**Pull request merged**
